name: Publish Package on Tag

on:
  push:
    tags:
      - 'v*' # This will trigger on any tag that starts with 'v'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@richardgaunt'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Check package.json version matches tag
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$VERSION" != "$PKG_VERSION" ]; then
            echo "Error: Tag version ($VERSION) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ env.VERSION }}
          body: |
            ## Changes in this Release
            
            - See the [CHANGELOG.md](./CHANGELOG.md) for details
            
            ## Installation
            
            ```bash
            # Install from GitHub Packages
            npm install -g @richardgaunt/cli-maker
            
            # Or use with npx
            npx @richardgaunt/cli-maker my-cli-app
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
